var a = Math.random(Math.round(1, 12));
var b = Math.random(Math.round(1, 12));
console.log(a);
console.log(b);
var add = a + b;
var sub = a - b;
var mul = a * b;
var div = Math.round(a / b);
console.log(add);
console.log(sub);
console.log(mul);
console.log(div);